---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sportlytics-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sportlytics-deployment
  labels:
    app: sportlytics
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sportlytics
  template:
    metadata:
      labels:
        app: sportlytics
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "mkdir -p /app/data && chown -R 1000:1000 /app/data && chmod 777 /app/data"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: db-data
          mountPath: /app/data
      containers:
      - name: sportlytics
        image: ghcr.io/pranjali2117/final_agentic:latest
        ports:
        - containerPort: 8501
        env:
        - name: DB_PATH
          value: "/app/data/sportlytics.db"
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: sportlytics-secrets
              key: GROQ_API_KEY
        - name: TAVILY_API_KEY
          valueFrom:
            secretKeyRef:
              name: sportlytics-secrets
              key: TAVILY_API_KEY
        volumeMounts:
        - name: db-data
          mountPath: /app/data
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: sportlytics-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sportlytics-service
spec:
  selector:
    app: sportlytics
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: LoadBalancer
